version: '3.4'

networks: 
  appNetwork:

services:
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    hostname: rabbit
    environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: mysecretpassword
    ports:
    - "5672:5672"
    - "30000:15672"   
    networks: 
      - appNetwork 
    
  stockconsumer:
    image: gamorim/stockconsumer
    container_name: stockconsumer
    restart: on-failure
    depends_on:
      - rabbit
    build:
      context: ./StockConsumer
      dockerfile: Dockerfile
    environment:
      RABBIT_MQ_HOST: rabbit
    networks: 
      - appNetwork
  
  chatapp:
    image: gamorim/chatapp
    container_name: chatapp
    restart: on-failure
    depends_on:
      - rabbit
    build:
      context: ./ChatApplication
      dockerfile: Dockerfile
    environment:
      RABBIT_MQ_HOST: rabbit
    ports:
    - "8080:80"
    networks: 
      - appNetwork

  rabbitmqworker:
    image: gamorim/rabbitmqworker
    container_name: rabbitmqworker
    restart: on-failure
    depends_on:
      - rabbit
      - chatapp
      - stockconsumer
    build:
      context: ./RabbitMqWorker
      dockerfile: Dockerfile
    environment:
      RABBIT_MQ_HOST: rabbit
    networks: 
      - appNetwork
    
  frontend:
    image: gamorim/frontend
    container_name: frontend
    restart: on-failure
    depends_on:
      - rabbit
      - chatapp
      - rabbitmqworker
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - "4200:80"
    networks: 
      - appNetwork